const MEMBER_POINT_SAVE = 'MEMBER_POINT_SAVE';
const MEMBER_POINT_SAVE_SUCCESS = 'MEMBER_POINT_SAVE_SUCCESS';
const MEMBER_POINT_SAVE_FAILURE = 'MEMBER_POINT_SAVE_FAILURE';
const MEMBER_LISTLOAD = 'MEMBER_LISTLOAD';
const MEMBER_LISTLOAD_SUCCESS = 'MEMBER_LISTLOAD_SUCCESS';
const MEMBER_LISTLOAD_FAILURE = 'MEMBER_LISTLOAD_FAILURE';
const MEMBER_EDIT = 'MEMBER_EDIT';
const MEMBER_EDIT_SUCCESS = 'MEMBER_EDIT_SUCCESS';
const MEMBER_EDIT_FAILURE = 'MEMBER_EDIT_FAILURE';
const MEMBER_DELETE = 'MEMBER_DELETE';
const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS';
const MEMBER_DELETE_FAILURE = 'MEMBER_DELETE_FAILURE';

export {
    MEMBER_POINT_SAVE,
    MEMBER_POINT_SAVE_SUCCESS,
    MEMBER_POINT_SAVE_FAILURE,
    MEMBER_LISTLOAD,
    MEMBER_LISTLOAD_SUCCESS,
    MEMBER_LISTLOAD_FAILURE,
    MEMBER_EDIT,
    MEMBER_EDIT_SUCCESS,
    MEMBER_EDIT_FAILURE,
    MEMBER_DELETE,
    MEMBER_DELETE_SUCCESS,
    MEMBER_DELETE_FAILURE
}